Merge branch 'latest' into 'master' for 0.13.0 release
Author: Jacob Maes <jmaes@linkedin.com>
Author: Bharath Kumarasubramanian <bkumaras@linkedin.com>
Author: Navina Ramesh <nramesh@linkedin.com>
Author: Jacob Maes <jacob.maes@gmail.com>
Author: vjagadish1989 <jvenkatr@linkedin.com>
Author: Yi Pan <nickpan47@gmail.com>
Author: Aleksandar Pejakovic <a.pejakovic@levi9.com>
Author: Ken Gidley <kgidley@yahoo.com>
Author: Xinyu Liu <xiliu@xiliu-ld.linkedin.biz>
Author: Yi Pan (Data Infrastructure) <nickpan47@gmail.com>
Author: Vishal Kuo <vishalkuo@gmail.com>
Author: Branislav Cogic <b.cogic@levi9.com>
Author: Stanislav Los <slos78@gmail.com>
Author: Steven Aerts <steven.aerts@gmail.com>
Author: Yan Fang <yanfang724@gmail.com>

Reviewers: Yi Pan (Data Infrastructure) <nickpan47@gmail.com>

Closes #21 from jmakes/master

diff --git a/bin/grid b/bin/grid
--- a/bin/grid
+++ b/bin/grid
@@ -35,9 +35,15 @@ DOWNLOAD_CACHE_DIR=$HOME/.samza/download
 COMMAND=$1
 SYSTEM=$2
 
-DOWNLOAD_KAFKA=http://www.us.apache.org/dist/kafka/0.10.0.1/kafka_2.11-0.10.0.1.tgz
+DOWNLOAD_KAFKA=http://www.us.apache.org/dist/kafka/0.10.1.1/kafka_2.11-0.10.1.1.tgz
 DOWNLOAD_YARN=https://archive.apache.org/dist/hadoop/common/hadoop-2.6.1/hadoop-2.6.1.tar.gz
 DOWNLOAD_ZOOKEEPER=http://archive.apache.org/dist/zookeeper/zookeeper-3.4.3/zookeeper-3.4.3.tar.gz
+
+SERVICE_WAIT_TIMEOUT_SEC=20
+ZOOKEEPER_PORT=2181
+RESOURCEMANAGER_PORT=8032
+NODEMANAGER_PORT=8042
+KAFKA_PORT=9092
 
 bootstrap() {
   echo "Bootstrapping the system..."
@@ -49,10 +55,26 @@ bootstrap() {
   exit 0
 }
 
+standalone() {
+  echo "Setting up the system..."
+  stop_all
+  rm -rf "$DEPLOY_ROOT_DIR"
+  mkdir "$DEPLOY_ROOT_DIR"
+  install_all_without_yarn
+  start_all_without_yarn
+  exit 0
+}
+
 install_all() {
   $DIR/grid install samza
   $DIR/grid install zookeeper
   $DIR/grid install yarn
+  $DIR/grid install kafka
+}
+
+install_all_without_yarn() {
+  $DIR/grid install samza
+  $DIR/grid install zookeeper
   $DIR/grid install kafka
 }
 
@@ -90,7 +112,7 @@ install_yarn() {
 
 install_kafka() {
   mkdir -p "$DEPLOY_ROOT_DIR"
-  install kafka $DOWNLOAD_KAFKA kafka_2.11-0.10.0.1
+  install kafka $DOWNLOAD_KAFKA kafka_2.11-0.10.1.1
   # have to use SIGTERM since nohup on appears to ignore SIGINT
   # and Kafka switched to SIGINT in KAFKA-1031.
   sed -i.bak 's/SIGINT/SIGTERM/g' $DEPLOY_ROOT_DIR/kafka/bin/kafka-server-stop.sh
@@ -122,10 +144,16 @@ start_all() {
   $DIR/grid start kafka
 }
 
+start_all_without_yarn() {
+  $DIR/grid start zookeeper
+  $DIR/grid start kafka
+}
+
 start_zookeeper() {
   if [ -f $DEPLOY_ROOT_DIR/$SYSTEM/bin/zkServer.sh ]; then
     cd $DEPLOY_ROOT_DIR/$SYSTEM
     bin/zkServer.sh start
+    wait_for_service "zookeeper" $ZOOKEEPER_PORT
     cd - > /dev/null
   else
     echo 'Zookeeper is not installed. Run: bin/grid install zookeeper'
@@ -135,7 +163,9 @@ start_zookeeper() {
 start_yarn() {
   if [ -f $DEPLOY_ROOT_DIR/$SYSTEM/sbin/yarn-daemon.sh ]; then
     $DEPLOY_ROOT_DIR/$SYSTEM/sbin/yarn-daemon.sh start resourcemanager
+    wait_for_service "resourcemanager" $RESOURCEMANAGER_PORT
     $DEPLOY_ROOT_DIR/$SYSTEM/sbin/yarn-daemon.sh start nodemanager
+    wait_for_service "nodemanager" $NODEMANAGER_PORT
   else
     echo 'YARN is not installed. Run: bin/grid install yarn'
   fi
@@ -147,9 +177,27 @@ start_kafka() {
     cd $DEPLOY_ROOT_DIR/$SYSTEM
     nohup bin/kafka-server-start.sh config/server.properties > logs/kafka.log 2>&1 &
     cd - > /dev/null
+    wait_for_service "kafka" $KAFKA_PORT
   else
     echo 'Kafka is not installed. Run: bin/grid install kafka'
   fi
+}
+
+wait_for_service() {
+  local SERVICE_NAME=$1
+  local PORT=$2
+  echo "Waiting for $SERVICE_NAME to start..."
+  local CURRENT_WAIT_TIME=0
+  until $(nc -w 1 localhost $PORT); do
+    printf '.'
+    sleep 1
+    if [ $((++CURRENT_WAIT_TIME)) -eq $SERVICE_WAIT_TIMEOUT_SEC ]; then
+      printf "\nError: timed out while waiting for $SERVICE_NAME to start.\n"
+      exit 1
+    fi
+  done
+  printf '\n'
+  echo "$SERVICE_NAME has started";
 }
 
 stop_all() {
@@ -191,6 +239,9 @@ stop_kafka() {
 if [ "$COMMAND" == "bootstrap" ] && test -z "$SYSTEM"; then
   bootstrap
   exit 0
+elif [ "$COMMAND" == "standalone" ] && test -z "$SYSTEM"; then
+  standalone
+  exit 0
 elif (test -z "$COMMAND" && test -z "$SYSTEM") \
   || ( [ "$COMMAND" == "help" ] || test -z "$COMMAND" || test -z "$SYSTEM"); then
   echo
@@ -198,6 +249,7 @@ elif (test -z "$COMMAND" && test -z "$SYSTEM") \
   echo
   echo "  $ grid"
   echo "  $ grid bootstrap"
+  echo "  $ grid standalone"
   echo "  $ grid install [yarn|kafka|zookeeper|samza|all]"
   echo "  $ grid start [yarn|kafka|zookeeper|all]"
   echo "  $ grid stop [yarn|kafka|zookeeper|all]"
